### PR TITLE
Correcting function name

### PR DESCRIPTION
**Pull request by NimbusFox**

### CODE REVIEW

**Comment by NimbusFox** [comment]
#35 Seems to have changed the wrong section

**Comment by raysan5** [comment]
@NimbusFox Oh! Thanks for the re-review! 👍😄

**Comment by Peter0x44** [comment]
@NimbusFox but this is still wrong? the function is InitAudioDevice
what was intended to be changed in the first place?

**Comment by NimbusFox** [comment]
@Peter0x44 Corrected the mistake in #39 thanks for pointing it out

**Pull request merged**
