### PR TITLE
Add Korean translation of the raylib API cheatsheet page

### PR DESCRIPTION
**Pull request by jdeokkim**
This (draft) pull request adds the Korean translation of the raylib API cheatsheet page.

## To-do list
- [ ] `module: rcore`
- [ ] `module: rshapes`
- [ ] `module: rtextures`
- [ ] `module: rtext`
- [ ] `module: rmodels`
- [ ] `module: raudio`
- [x] `structs`
- [x] `colors`

### CODE REVIEW

**Comment by raysan5** [comment]
@jdeokkim This is really nice! Thank you very much for working on this!

**Comment by jdeokkim** [comment]
> @jdeokkim What is the state of this PR?

We were working on the `rcore`, `rshapes` and `rtext` modules, but we couldn't finish them last year because we've been busy studying at our universities... We'll try to work on them again with the changes from the 'master' branch during this summer vacation, sorry!

**Comment by raysan5** [comment]
@jdeokkim Ok, no worries! Thanks for the quick update! Just note the cheatsheet page is being slightly redesign and it could affect this PR.

**Comment by jdeokkim** [comment]
We'll keep that in mind, thank you very much!

**Comment by jdeokkim** [comment]
Hello, we decided to submit multiple pull requests to complete the translations of the cheatsheet, instead of trying to finish everything at once. I'll create a new one in a few weeks based on the current version of the translated cheatsheet that we have!

**Pull request closed without merging**
